name: Build and Deploy

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: cp package*.json ./dist/
      - run: node --version > ./dist/.nvmrc
      - uses: ./.github/workflows/deploy
        with:
          port: ${{ secrets.PORT }}
          environment: preview
        secrets:
          ssh-host: ${{ secrets.STAGING_SSH_HOST }}
          ssh-key: ${{ secrets.STAGING_SSH_KEY }}
          ssh-user: ${{ secrets.STAGING_SSH_USER }}
