on:
  workflow_call:
    inputs:
      node_version:
        type: string
        required: true
      port:
        type: number
        required: true
      environment:
        type: string
        required: true
jobs:
  build:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: cp package*.json ./dist/
    - run: node --version > ./dist/.nvmrc
    - name: Update environment info
      run: |
        cat <<EOD>./dist/.env
          PORT=${{ inputs.port }}
          ENVIRONMENT="${{ inputs.environment }}"
          BUILD_INFO="${BUILD_INFO}"
        EOD
      env:
        BUILD_INFO: "Build ${{ github.run_number }}.${{ github.run_attempt }} from ${{ github.ref_name }}"
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist
