on:
  workflow_call:
    secrets:
      ssh-host:
        required: true
      ssh-key:
        required: true
      ssh-user:
        required: true  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.ssh-host }}
          SSH_KEY: ${{ secrets.ssh-key }}
          SSH_USER: ${{ secrets.ssh-user }}
      - name: Deploy code
        run: rsync -az dist staging:loadouts/preview/${{ github.run_number }}
