name: Build and Deploy

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: preview
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Update environment info
        run: |
          cat <<EOD>./dist/.env
            PORT=${PORT}
            ENVIRONMENT="${ENVIRONMENT}"
            BUILD_INFO="${BUILD_INFO}"
          EOD
        env:
          PORT: ${{ env.PORT }}
          ENVIRONMENT:  ${{ env.ENVIRONMENT }}
          BUILD_INFO: "Build ${{ github.build_number }}. ${{ github.run_attempt }} from ${{ github.ref_name }}"
